[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
local_solana_migrate = "GYAAArQX2sW9ju2FqXawS73bSjA3JwHKT2gmyLWsRZeN"

[programs.devnet]
local_solana_migrate = "3ZCPySRfFaDPthn5G5en7WzvZd5dtv3XvBR7zjHVRxZh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build-localnet = "anchor build --features localnet"
build-devnet = "anchor build --features devnet"
deploy-localnet = "anchor deploy --provider.cluster localnet --features localnet"
deploy-devnet = "anchor deploy --provider.cluster devnet --features devnet"
